# aiogram
BOT_TOKEN = '<TELEGRAM TOKEN>'
TELEGRAM_CHAR_LIMIT = 255
# mysql
HOST = "<DB IP>"
USER = "<DB USERNAME>"
PASSWORD = "<DB PASSWORD>"
NAME = "<DB NAME>"
PORT = 3306

# Constants
OPEN_AI_KEY = "<OPENAI API KEY>"
DEFAULT_TOKEN_NUM = 1000
MAX_TOKEN_NUM = 4096
INLINE_DEF_TOKEN_NUM = 400
INLINE_MAX_TOKEN_NUM = 1000
BOT_ROLE = "assistant"
USER_ROLE = "user"

BASIC_LANGUAGE = "en"
INFO_PHOTO = "INFO URL PHOTO"
WARNING_PHOTO = "WARNING URL PHOTO"
MISTAKE_PHOTO = "MISTAKE URL PHOTO"
END_TIP_PROBABILITY = 0.7
WAIT_TIME = 30
