# aiogram
BOT_TOKEN = ''
TELEGRAM_CHAR_LIMIT = 255  # Symbols
TG_INLINE_TIME_LIMIT = 10  # Seconds
OFERTA_FILE_ID = ""
INTRO_FILE_ID = ""
VISA_MC_FILE_ID = ""

# mysql
HOST = ""
USER = ""
PASSWORD = ""
NAME = ""
PORT = 3306

# Constants
ADMIN_CHAT_ID = 123
OPEN_AI_KEY = ""
DEFAULT_TOKEN_NUM = 1000
MAX_TOKEN_NUM = 4096
INLINE_DEF_TOKEN_NUM = 400
INLINE_MAX_TOKEN_NUM = 1000
BOT_ROLE = "assistant"
USER_ROLE = "user"

BASIC_LANGUAGE = "en"
INFO_PHOTO = "https://information.png"
WARNING_PHOTO = "https://warning.png"
MISTAKE_PHOTO = "https://cancel.png"
ANSWER_PHOTO = "https://answer.png"
END_TIP_PROBABILITY = 0.7
WAIT_TIME = 30
MISTAKE_WAIT_TIME = 5
SUBSCRIPTION_PRICE = 10  # USD
PAY_WAIT_TIME = 300  # sec
PAY_CHECK_INTERVAL = 10  # s
QUERY_WAIT_TIME = 30  # sec
QUERY_CHECK_INTERVAL = 3  # sec

# CryptoBot
CRYPTOBOT_TOKEN = ''

# coinmarketcap
CURRENCIES_API_KEY = "0be665af-2279-4062-978e-8641020fe640"

# WayForPay
WAYFORPAY_TOKEN = ""
LIQ_PAY_TOKEN = ""
